version: "3.8"

services:
  postgres:
    image: postgres
    container_name: postgres-sql-wac
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: mydb
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - whatsapp-clone
    restart: unless-stopped

  keycloak:
    container_name: keycloak-wac
    image: quay.io/keycloak/keycloak:26.0.0
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "9090:8080"
    networks:
      - whatsapp-clone
    volumes:
      - keycloak_data:/opt/keycloak/data
    command: ["start-dev"]

networks:
  whatsapp-clone:
    driver: bridge

volumes:
  postgres_data:  # Fixed volume name
    driver: local
  keycloak_data:  # Added missing Keycloak volume
    driver: local
